/usr/lib/oracle/18.3/client64/bin/sqlplus -s {string_connection} <<EOF

SET MARKUP CSV ON delimiter "|"

SELECT a.CP_ID,b.NAME,a.SERVICE_CODE AS OFFER_CODE,a.CONNECTION_NAME
,DECODE(a.CONNECTION_TYPE,'1','HTTP','0','SMPP') AS CONNECTION_TYPE,a.SYSTEM_ID,a.PASSWORD
,DECODE(a.SUBSCRIPTION_TYPE,'5','Bulk') AS SUBSCRIPTION_TYPE,a.STATUS
,DECODE(a.BIND_TYPE,'3','TranReceiver') AS BIND_TYPE,a.MAX_CONCURRENT_CONNECTION,a.TPS,a.BUFFER
,DECODE(a.DRE_ENABLED,'1','Enable','0','Disable') AS DRE_ENABLED
,DECODE(a.MO_DR_TYPE,'1','Round Robin')AS MO_DR_TYPE,a.MO_URL_1,a.DR_URL1 
FROM SCMUSER.SUBSCRIPTION_CP_CONNECTION a
LEFT JOIN SCMUSER.PROVIDER_CP b ON a.CP_ID=b.CP_ID
WHERE a.CP_ID ='{cpid}';

SPOOL OFF
EXIT
EOF