/usr/lib/oracle/18.3/client64/bin/sqlplus -s {string_connection} <<EOF

SET MARKUP CSV ON delimiter "|"

SELECT TO_CHAR(CDR_TIMESTAMP,'dd-mm-yyyy') CDRDATE,COUNT(TRANSACTION_ID) TOTAL
FROM
(SELECT CDR_TIMESTAMP,TRANSACTION_ID,DIAMETER_RESULT_CODES
FROM SCPCDR.INTERNAL_CDR_{day}
WHERE M_MONTH= '{mon}'
UNION ALL
SELECT CDR_TIMESTAMP,TRANSACTION_ID,DIAMETER_RESULT_CODES
FROM SCPCDR.INTERNAL_CDR_{day}@scpcdr_prod_pk_public
WHERE M_MONTH= '{mon}'
)
WHERE DIAMETER_RESULT_CODES='{diameter}'
GROUP BY TO_CHAR(CDR_TIMESTAMP,'dd-mm-yyyy');

SPOOL OFF
EXIT
EOF