/usr/lib/oracle/18.3/client64/bin/sqlplus -s {string_connection} <<EOF


SET MARKUP CSV ON delimiter "|"

SELECT CP_ID,CP_NAME,OFFER_CODE ,OFFER_NAME,OFFER_DESC,SHORT_CODE,SUBSCRIPTION_MODE
,AUTO_RENEWAL_MAX_SPAN,CODE_ARGUMENT,STATUS,CHANNEL_ID,AUTO_DEACTIVATION_RULE,TYPE_OF_SERVICE
,CP_NOTIFICATION,KEYWORD,TO_CHAR(CREATE_DATE,'yyyy-mm-dd HH24:MI') CREATE_DATE
,TO_CHAR(UPDATE_DATE,'yyyy-mm-dd HH24:MI') UPDATE_DATE
FROM SCMUSER.SUBSCRIPTION_OFFER
{condition};

SPOOL OFF
EXIT
EOF